### ISSUE TITLE
How to configure the parameters of define.v ?

### ISSUE THREAD

**Issue by zzulb** [kemalderya/pqc-param-ntt#2]
Hi, I ran your code, but always got errors. How to configure the parameters of the define.v file, if I use the kyber1_1pe.v simulation file.

\`define PE	1
\`define PE_DEPTH	($clog2(\`PE))

\`define DATA_SIZE	256>> \`PE_DEPTH
\`define DATA_SIZE_TW	256>> (\`PE_DEPTH >> 1)
\`define BRAM_DEPTH	($clog2(256>> \`PE_DEPTH))
\`define TW_DEPTH	($clog2(256>> (\`PE_DEPTH >> 1)))
\`define MAX	9'd511

\`define RING_SIZE	256
\`define RING_DEPTH	($clog2(\`RING_SIZE))

Do I still need to modify the NTT1024.v file?

**Comment by kemalderya** [comment]
In defines.v file, you only need to change PE parameter to 1 since you want to use 1 PE. Other parameters should be the same. You don't need to modify NTT1024.v file.

**Comment by aledolme** [comment]
Hi! I'm running your code too and I' always getting as calculated result "xxxxxxx".
Is there any other modification thay should be perfomed to the file?
Thanks

**Comment by bpradeep508** [comment]
Did you solve the problem. In my case  facing same issue

**Comment by bpradeep508** [comment]
Wrong result -- index:          0, expected:000017ec --> calculated:xxxxxxxx
Wrong result -- index:          1, expected:00000f2d --> calculated:xxxxxxxx
Wrong result -- index:          2, expected:000015c5 --> calculated:xxxxxxxx
Wrong result -- index:          3, expected:0000184f --> calculated:xxxxxxxx
Wrong result -- index:          4, expected:00000e1d --> calculated:xxxxxxxx
Wrong result -- index:          5, expected:00001a76 --> calculated:xxxxxxxx
Wrong result -- index:          6, expected:00000273 --> calculated:xxxxxxxx same happened for all indexex

**Comment by Kyrie-T** [comment]
Did you solve the problem. In my case facing same issue

**Comment by 4xDannycool** [comment]
> Did you solve the problem. In my case facing same issue

Did you solve the problem. In my case facing same issue

**Comment by 4xDannycool** [comment]
Did you solve the problem. In my case facing same issue
